" Enable syntax highlighting
syntax on

" Set file type plugin and indentation
filetype plugin indent on

" Enable line numbers
set number
"set relativenumber   " Show relative line numbers

" Word wrap ?
set wrap

" Set tab width to 4 spaces for C++
set tabstop=4
set shiftwidth=4
set expandtab

" Enable auto indentation
set autoindent
set smartindent

" Enable code folding
set foldmethod=syntax    " Fold based on syntax
set foldlevelstart=99    " Start with all folds open

" Enable auto-completion
set completeopt=menuone,noinsert,noselect
set shortmess+=c

" Enable search highlighting
set ignorecase           " Ignore case in search patterns
set smartcase            " Override ignorecase if search pattern contains uppercase
set hlsearch
set incsearch

" Enable line wrapping
set nowrap

" Set color scheme
colorscheme desert

" Enable mouse support
set mouse=a

" Show matching parentheses
set showmatch

" Map keys for faster navigation
nnoremap <C-n> :bnext<CR>
nnoremap <C-p> :bprev<CR>

" Set C++ specific settings
autocmd FileType cpp setlocal tabstop=4 shiftwidth=4 expandtab

" Highlight the current line
set cursorline

" Key mappings to save / compile code
nnoremap <F5> :w<CR>:!clang++ -g -o %:r % -O0<CR>
